import React,{useEffect,useMemo,useState}from'react';
import{CheckCircle2,ChevronRight,FolderPlus,Package,Plus,Save,Sparkles,Trash2,X}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{auth,removeUserDocument,saveUserDocument,subscribeToUserCollection}from'../../lib/supabase';

import { ProductImages } from './ProductImages';
import { CatalogPreview } from './CatalogPicker';
import { catalogProblem } from '../../lib/catalogs';

type Catalog={id:string;name:string;description:string;active:boolean;updated_at?:string};
type Product={images?:string[];id:string;catalog_id?:string;name:string;price:string;description:string;url:string;active:boolean;updated_at?:string};
const DEFAULT_ID='default';

export const CatalogPage:React.FC=()=>{
 const{setActiveTab,setIsBuilderOpen,workspaceId}=useApp();
 const[catalogs,setCatalogs]=useState<Catalog[]>([]);
 const[products,setProducts]=useState<Product[]>([]);
 const[selected,setSelected]=useState(DEFAULT_ID);
 const[newCatalog,setNewCatalog]=useState(false);
 const[catalogName,setCatalogName]=useState('');
 const[catalogDesc,setCatalogDesc]=useState('');
 const[draft,setDraft]=useState<Omit<Product,'id'>>({catalog_id:DEFAULT_ID,name:'',price:'',description:'',url:'',active:true});
 const[saving,setSaving]=useState(false);
 const[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const run=async(action:()=>Promise<void>)=>{setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.');}};

 useEffect(()=>{setUploading(false);setCatalogs([]);setProducts([]);setSelected(DEFAULT_ID);setDraft({catalog_id:DEFAULT_ID,name:'',price:'',description:'',url:'',active:true});const uid=workspaceId||auth.currentUser?.uid;if(!uid)return;const a=subscribeToUserCollection<Catalog>(uid,'catalogs',setCatalogs);const b=subscribeToUserCollection<Product>(uid,'catalog_products',setProducts);return()=>{a?.();b?.()}},[workspaceId]);
 const allCatalogs=useMemo(()=>[catalogs.find(c=>c.id===DEFAULT_ID)||{id:DEFAULT_ID,name:'Main Catalog',description:'Your default product collection',active:true} as Catalog,...catalogs.filter(x=>x.id!==DEFAULT_ID)],[catalogs]);
 const current=allCatalogs.find(x=>x.id===selected)||allCatalogs[0];
 const visible=products.filter(p=>(p.catalog_id||DEFAULT_ID)===selected);

 const createCatalog=async()=>{const uid=workspaceId||auth.currentUser?.uid;const name=catalogName.trim();if(!uid||!name)return;const item={id:'catalog_'+Date.now(),name,description:catalogDesc.trim(),active:true,updated_at:new Date().toISOString()};await saveUserDocument(uid,'catalogs',item);setSelected(item.id);setDraft(p=>({...p,catalog_id:item.id}));setCatalogName('');setCatalogDesc('');setNewCatalog(false)};
 const addProduct=async()=>{const uid=workspaceId||auth.currentUser?.uid;if(!uid||!draft.name.trim())return;if(!draft.images?.length)throw Error('Upload at least one product image.');if(draft.url&&!/^https:\/\//.test(draft.url))throw Error('Use an HTTPS product link.');setSaving(true);try{await saveUserDocument(uid,'catalog_products',{id:'product_'+Date.now(),...draft,catalog_id:selected,name:draft.name.trim(),updated_at:new Date().toISOString()});setDraft({catalog_id:selected,name:'',price:'',description:'',url:'',active:true})}finally{setSaving(false)}};
 const saveProduct=async(p:Product)=>{if(!p.name.trim()||p.active&&!p.images?.length)throw Error('Active products need a name and at least one image.');if(p.url&&!/^https:\/\//.test(p.url))throw Error('Use an HTTPS product link.');const uid=workspaceId||auth.currentUser?.uid;if(uid)await saveUserDocument(uid,'catalog_products',{...p,catalog_id:p.catalog_id||DEFAULT_ID,updated_at:new Date().toISOString()})};
 const removeProduct=async(p:Product)=>{const uid=workspaceId||auth.currentUser?.uid;if(uid&&window.confirm('Delete '+p.name+'?'))await removeUserDocument(uid,'catalog_products',p.id)};
 const deleteCatalog=async()=>{const uid=workspaceId||auth.currentUser?.uid;if(!uid||selected===DEFAULT_ID)return;if(!window.confirm('Delete this catalog? Products inside it will also be deleted.'))return;for(const p of visible)await removeUserDocument(uid,'catalog_products',p.id);await removeUserDocument(uid,'catalogs',selected);setSelected(DEFAULT_ID);setDraft(d=>({...d,catalog_id:DEFAULT_ID}))};
 const useInAi=()=>{sessionStorage.setItem('autoreply:prefill-catalog',selected);const lines=visible.filter(p=>p.active).map(p=>'- '+p.name+(p.price?' | Price: '+p.price:'')+(p.description?' | '+p.description:'')+(p.url?' | Link: '+p.url:''));sessionStorage.setItem('autoreply:prefill-ai-prompt','# PRODUCT CATALOG: '+current.name+'\n'+(lines.join('\n')||'No active products.')+'\n\nOnly recommend products from this catalog. Never invent price, stock or links.');setActiveTab('automations');setIsBuilderOpen(true)};

 return <div className="min-h-full bg-[#F7FAFF] px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl space-y-6">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Instagram product catalogs</p><h1 className="mt-1 text-2xl font-bold text-slate-950 sm:text-3xl">Catalogs</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Create separate catalogs for different businesses, categories or campaigns. Upload product photos and details, then share swipeable catalogs through DM Reply or AI DM Conversation. Each message supports up to 10 image cards.</p></div><button disabled={uploading||saving} onClick={()=>setNewCatalog(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-xs font-bold text-white"><FolderPlus className="h-4 w-4"/>New catalog</button></header>

  {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-600">{error}</p>}
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{allCatalogs.map(c=>{const count=products.filter(p=>(p.catalog_id||DEFAULT_ID)===c.id).length;const on=selected===c.id;return <button key={c.id} disabled={uploading||saving} onClick={()=>{setSelected(c.id);setDraft({catalog_id:c.id,name:'',price:'',description:'',url:'',active:true,images:[]})}} className={`rounded-2xl border p-4 text-left transition ${on?'border-indigo-400 bg-indigo-50 ring-2 ring-indigo-100':'border-slate-200 bg-white hover:border-indigo-200'}`}><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${on?'bg-indigo-600 text-white':'bg-slate-50 text-slate-500'}`}><Package className="h-5 w-5"/></span><ChevronRight className="h-4 w-4 text-slate-300"/></div><h3 className="mt-3 text-sm font-bold text-slate-900">{c.name}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{c.description||'Product collection'}</p><p className="mt-3 text-xs font-bold text-indigo-600">{count} product{count===1?'':'s'}</p></button>})}</section>

  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Selected catalog</p><h2 className="mt-1 text-lg font-bold text-slate-950">{current.name}</h2><p className="mt-1 text-xs text-slate-500">Products below are only part of this catalog.</p></div><div className="flex gap-2">{selected!==DEFAULT_ID&&<button onClick={()=>void run(deleteCatalog)} className="h-10 rounded-xl border border-rose-200 px-3 text-xs font-bold text-rose-600">Delete catalog</button>}<button disabled={Boolean(catalogProblem(current,visible))} onClick={useInAi} className="inline-flex h-10 items-center gap-2 rounded-xl bg-indigo-600 px-4 text-xs font-bold text-white disabled:opacity-40"><Sparkles className="h-4 w-4"/>Use in AI</button></div></div></section>

  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-xs font-semibold text-slate-700">Catalog name<input key={current.id+current.name} defaultValue={current.name} maxLength={80} onBlur={e=>{const name=e.target.value.trim();if(name&&name!==current.name)void run(()=>saveUserDocument(workspaceId,'catalogs',{...current,name,updated_at:new Date().toISOString()}));}} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label><label className="flex items-center gap-2 text-xs font-semibold text-slate-600"><input type="checkbox" checked={current.active} onChange={e=>void run(()=>saveUserDocument(workspaceId,'catalogs',{...current,active:e.target.checked,updated_at:new Date().toISOString()}))}/>Active catalog</label></div><p className="mt-3 text-xs text-slate-500">Each photo becomes one swipeable card, with the product name, price and description below it. Instagram displays up to 80 characters in card titles and descriptions.</p>{catalogProblem(current,visible)?<p className="mt-3 text-xs text-amber-700">{catalogProblem(current,visible)}</p>:<div className="mt-5"><CatalogPreview products={visible}/></div>}</section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <h2 className="text-lg font-semibold text-slate-900">Add a product</h2>
    <p className="mt-1 text-sm text-slate-500">Add approved details to {current.name}. Leave price blank when you do not want AI to quote it.</p>
    <ProductImages key={workspaceId+selected} workspaceId={workspaceId} catalogId={selected} images={draft.images||[]} onChange={images=>setDraft(p=>({...p,images}))} onBusy={setUploading}/>
    <div className="mt-4 grid gap-4 md:grid-cols-2">
      <label className="text-sm font-medium text-slate-700">Product name<input value={draft.name} onChange={e=>setDraft(p=>({...p,name:e.target.value}))} placeholder="Example: Heart photo frame" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label>
      <label className="text-sm font-medium text-slate-700">Price <span className="font-normal text-slate-500">(optional)</span><input value={draft.price} onChange={e=>setDraft(p=>({...p,price:e.target.value}))} placeholder="Example: ₹399" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label>
      <label className="text-sm font-medium text-slate-700 md:col-span-2">Description & variants<textarea value={draft.description} onChange={e=>setDraft(p=>({...p,description:e.target.value}))} placeholder="Available shapes, customization and confirmed stock information" rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/></label>
      <label className="text-sm font-medium text-slate-700">Product link <span className="font-normal text-slate-500">(optional)</span><input value={draft.url} onChange={e=>setDraft(p=>({...p,url:e.target.value}))} placeholder="https://your-store.com/product" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label>
      <button onClick={()=>void run(addProduct)} disabled={saving||uploading||!draft.name.trim()||!draft.images?.length} className="inline-flex h-11 items-center justify-center gap-2 self-end rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white disabled:opacity-50"><Plus className="h-4 w-4"/>{saving?'Saving…':'Add product'}</button>
    </div>
  </section>

  <section className="grid gap-4 md:grid-cols-2">{visible.length?visible.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><Package className="h-4 w-4"/></span><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={item.active} onChange={e=>setProducts(prev=>prev.map(p=>p.id===item.id?{...p,active:e.target.checked}:p))}/>Active</label></div><ProductImages key={workspaceId+item.id} workspaceId={workspaceId} catalogId={selected} images={item.images||[]} onChange={images=>setProducts(prev=>prev.map(p=>p.id===item.id?{...p,images}:p))} onBusy={setUploading}/><input aria-label="Product name" value={item.name} onChange={e=>setProducts(prev=>prev.map(p=>p.id===item.id?{...p,name:e.target.value}:p))} className="mt-4 w-full text-base font-bold text-slate-900 outline-none"/><input aria-label="Product price" value={item.price} onChange={e=>setProducts(prev=>prev.map(p=>p.id===item.id?{...p,price:e.target.value}:p))} placeholder="Price" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><textarea aria-label="Product description" value={item.description} onChange={e=>setProducts(prev=>prev.map(p=>p.id===item.id?{...p,description:e.target.value}:p))} rows={3} className="mt-2 w-full rounded-lg border border-slate-200 p-3 text-sm"/><input aria-label="Product link" value={item.url} onChange={e=>setProducts(prev=>prev.map(p=>p.id===item.id?{...p,url:e.target.value}:p))} placeholder="Product URL" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><div className="mt-4 flex gap-2"><button disabled={uploading} onClick={()=>void run(()=>saveProduct(item))} className="inline-flex h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-indigo-600 text-xs font-bold text-white"><Save className="h-4 w-4"/>Save</button><button aria-label={'Delete '+item.name} onClick={()=>void run(()=>removeProduct(item))} className="flex h-10 w-10 items-center justify-center rounded-xl border border-rose-200 text-rose-600"><Trash2 className="h-4 w-4"/></button></div></article>):<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500 md:col-span-2">No products yet. Add your first product above, then use this catalog in your AI setup.</div>}</section>

  {newCatalog&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">New collection</p><h3 className="mt-1 text-lg font-bold text-slate-950">Create catalog</h3></div><button aria-label="Close new catalog" onClick={()=>setNewCatalog(false)} className="rounded-lg border border-slate-200 p-2 text-slate-500"><X className="h-4 w-4"/></button></div><input autoFocus value={catalogName} onChange={e=>setCatalogName(e.target.value)} placeholder="Catalog name" className="mt-4 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/><textarea value={catalogDesc} onChange={e=>setCatalogDesc(e.target.value)} placeholder="What is this catalog for?" rows={3} className="mt-3 w-full rounded-xl border border-slate-200 p-3 text-sm"/><button onClick={()=>void run(createCatalog)} disabled={!catalogName.trim()} className="mt-4 h-11 w-full rounded-xl bg-indigo-600 text-xs font-bold text-white disabled:opacity-50">Create catalog</button></div></div>}
 </div></div>
};
