import React,{useState,useEffect,useRef} from 'react';
import { ImagePlus, X } from 'lucide-react';
import { uploadCatalogImages } from '../../lib/catalogs';
export function ProductImages({workspaceId,catalogId,images,onChange,onBusy}:{workspaceId:string;catalogId:string;images:string[];onChange:(images:string[])=>void;onBusy?:(busy:boolean)=>void}) {
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;}},[]);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const upload=async(files:File[])=>{if(!files.length||busy)return;setError('');if(images.length+files.length>10){setError('Keep up to 10 images per product.');return;}setBusy(true);onBusy?.(true);try{const urls=await uploadCatalogImages(workspaceId,catalogId,files);if(mounted.current)onChange([...images,...urls]);}catch(e){setError(e instanceof Error?e.message:'Upload failed. Please retry.');}finally{if(mounted.current){setBusy(false);onBusy?.(false);}}};
 return <div className="mt-4"><p className="text-xs font-semibold text-slate-700">Product images · JPG, PNG or WebP · Up to 5 MB each</p><div className="mt-2 flex flex-wrap gap-2">{images.map((url,i)=><div key={url} className="relative"><img src={url} alt={'Product image '+(i+1)} className="h-24 w-24 rounded-xl border border-slate-200 object-cover"/><button disabled={busy} type="button" aria-label={'Remove image '+(i+1)} onClick={()=>onChange(images.filter((_,j)=>j!==i))} className="absolute right-1 top-1 rounded-full bg-white p-1 shadow"><X className="h-3 w-3"/></button></div>)}<label className="flex h-24 w-24 cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border border-dashed border-indigo-300 bg-indigo-50 text-xs font-semibold text-indigo-700"><ImagePlus className="h-5 w-5"/>{busy?'Uploading…':'Add images'}<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} aria-label="Upload product images" className="sr-only" onChange={e=>{void upload(Array.from(e.target.files||[]));e.target.value='';}}/></label></div>{error&&<p role="alert" className="mt-2 text-xs text-rose-600">{error}</p>}</div>;
}
