import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import vm from 'node:vm';import {transform} from 'esbuild';
const source=(await fs.readFile(new URL('../supabase/functions/instagram-live-webhook/index.ts',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
const compiled=await transform(source+'\nglobalThis.syncHelpers={inferCustomerInsight,syncAiLeadToGoogleSheet};',{loader:'ts',format:'esm'});
function setup(){
 const docs=new Map(),grids=new Map(),calls=[];let fail=false;
 const key=(c,id)=>c+':'+id;
 docs.set(key('google_sheets_connections','primary'),{connected:true,access_token:'test-google',expires_at:Date.now()+3600000});
 docs.set(key('contacts','canonical'),{ig_user_id:'new-scoped-id',ig_user_ids:['old-scoped-id','new-scoped-id'],ig_username:'asha'});
 for(const id of ['auto_one','auto_two'])docs.set(key('google_sheets_automations',id),{spreadsheet_id:id,fields:['Name','Phone'],state:'ready',sheet_name:'Leads',history_sheet:'Conversation history'});
 const admin={from(table){let filter={},mutation=null;const q={select(){return q},eq(k,v){filter[k]=v;return q},order(){return q},limit(){return q},upsert(value){mutation={kind:'upsert',value};return q},update(value){mutation={kind:'update',value};return q},delete(){mutation={kind:'delete'};return q},maybeSingle(){return result(true)},then(resolve,reject){return result(false).then(resolve,reject)}};
 async function result(single){if(table==='autoreply_sheet_sync_leases')return {data:null,error:null};if(mutation){const v=mutation.value;if(mutation.kind==='upsert')docs.set(key(v.collection,v.id),structuredClone(v.data));if(mutation.kind==='update')docs.set(key(filter.collection,filter.id),structuredClone(v.data));return {data:null,error:null};}const rows=[...docs].filter(([id])=>id.startsWith(filter.collection+':')&&(!filter.id||id===key(filter.collection,filter.id))).map(([id,data])=>({id:id.slice(filter.collection.length+1),data:structuredClone(data)}));return {data:single?rows[0]||null:rows,error:null};}return q;},async rpc(){return {data:true,error:null}}};
 const fakeFetch=async(url,init={})=>{url=String(url);calls.push({url,method:init.method||'GET'});if(fail&&url.includes('sheets.googleapis.com')){fail=false;return new Response(JSON.stringify({error:{message:'Sheets unavailable'}}),{status:503});}
 if(url.includes('api.openai.com')){const prompt=JSON.parse(init.body).messages[1].content;return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(prompt.includes('9876543210')?{Phone:'9876543210'}:{Name:'Asha'})}}]}));}
 if(url.includes('?fields='))return new Response(JSON.stringify({sheets:[{properties:{title:'Leads'}},{properties:{title:'Conversation history'}}]}));
 const match=url.match(/spreadsheets\/([^/]+)\/values\/([^?]+)/);if(!match)throw Error('Unexpected '+url);const sheet=match[1],range=decodeURIComponent(match[2]).replace(/:append$/,''),tab=range.split('!')[0].replace(/'/g,''),gridKey=sheet+':'+tab;const grid=grids.get(gridKey)||[];grids.set(gridKey,grid);
 if(init.method==='PUT'){const index=Number(range.split('!')[1].match(/\d+/)?.[0]||1)-1;const values=JSON.parse(init.body).values;values.forEach((row,i)=>grid[index+i]=row);return new Response('{}');}
 if(init.method==='POST'){grid.push(...JSON.parse(init.body).values);return new Response(JSON.stringify({updates:{updatedRange:tab+'!A'+grid.length}}));}
 return new Response(JSON.stringify({values:grid}));};
 const ctx={Response,Request,Headers,URL,URLSearchParams,TextEncoder,crypto,AbortSignal,setTimeout,clearTimeout,setInterval,clearInterval,performance,console,fetch:fakeFetch,createClient:()=>admin,Deno:{env:{get:()=>''},serve:()=>{}}};vm.createContext(ctx);vm.runInContext(compiled.code,ctx);
 const sync=(text,id='auto_one',msg=crypto.randomUUID(),sender='new-scoped-id')=>ctx.syncHelpers.syncAiLeadToGoogleSheet(admin,'workspace',sender,text,[],'openai-test',id,msg,'Business reply');
 return {docs,grids,calls,sync,infer:ctx.syncHelpers.inferCustomerInsight,failNext(){fail=true}};
}
test('customer estimates separate purchase intent, objections and support; never infer paid customer',()=>{const f=setup();assert.equal(f.infer('Payment link please').stage,'ready');assert.equal(f.infer('not interested').priority,'low');assert.equal(f.infer('refund please').stage,'support');assert.notEqual(f.infer('I paid already').stage,'customer');const manual={stage:'repeat',priority:'high',source:'manual',reason:'Confirmed by owner'};assert.deepEqual(f.infer('not interested',manual),manual);});
test('follow-up updates one customer row, preserves known details and records each chat once',async()=>{const f=setup();await f.sync('My name is Asha','auto_one','event1');await f.sync('Phone 9876543210','auto_one','event2','old-scoped-id');await f.sync('Phone 9876543210','auto_one','event2','old-scoped-id');const rows=f.grids.get('auto_one:Leads');assert.equal(rows.length,2);assert.equal(rows[1][0],'Asha');assert.equal(rows[1][1],'9876543210');assert.equal(rows[1][5],'canonical');const history=f.grids.get('auto_one:Conversation history');assert.equal(history.length,3);assert.equal(history[1][4],'My name is Asha');assert.equal(history[1][5],'Business reply');});
test('two automations write to their own spreadsheets',async()=>{const f=setup();await f.sync('My name is Asha','auto_one');await f.sync('Phone 9876543210','auto_two');assert.equal(f.grids.get('auto_one:Leads')[1][1],'');assert.equal(f.grids.get('auto_two:Leads')[1][1],'9876543210');});
test('Sheets outage retains pending information and logs the error; next conversation drains it',async()=>{const f=setup();f.failNext();await f.sync('My name is Asha','auto_one','failed-event');assert.equal(f.docs.get('sheet_sync_jobs:auto_one:failed-event').status,'pending');assert.ok([...f.docs].some(([key,value])=>key.startsWith('webhook_events:')&&value.reason==='google_sheet_sync_failed'));await f.sync('Phone 9876543210','auto_one','next-event');assert.equal(f.docs.get('sheet_sync_jobs:auto_one:failed-event').status,'synced');assert.equal(f.grids.get('auto_one:Leads')[1][0],'Asha');assert.equal(f.grids.get('auto_one:Leads')[1][1],'9876543210');});
