import React,{useEffect,useMemo,useState,useRef}from'react';
import{ArrowLeft,Bot,Check,ChevronRight,Clock,Image as ImageIcon,Instagram,LoaderCircle,MessageCircle,MessageSquare,MoreHorizontal,Phone,Video,Camera,Mic,Smile,Info,Plus,Send,Sparkles,Trash2,X,Zap}from'lucide-react';
import{useApp}from'../../context/AppContext';
import { AutomationReviewPhone } from './AutomationReviewPhone';
import { uniqueAutomationName } from '../../lib/automationPresentation';
import { CatalogPicker } from '../Catalog/CatalogPicker';
import { catalogProblem, useCatalogs } from '../../lib/catalogs';
import { AiAssistantSetup } from './AiAssistantSetup';
import{SmartPromptAnalyzer}from'./SmartPromptAnalyzer';
import{ActionItem,Automation,TriggerConfig,TriggerType}from'../../types';

type Media={id:string;content_type?:string;media_type?:string;caption?:string;media_url?:string;thumbnail_url?:string;permalink?:string};
const readBuilderPreference=(key:string,fallback:string)=>{try{return localStorage.getItem(key)||fallback}catch{return fallback}};
const kinds:{id:TriggerType;title:string;desc:string;icon:any}[]=[
 {id:'comment',title:'Comment Automation',desc:'Reply to comments on a selected post or reel.',icon:MessageSquare},
 {id:'story_reply',title:'Story Reply',desc:'Reply when someone responds to a selected active story.',icon:Instagram},
 {id:'dm',title:'DM Reply',desc:'Send a fixed reply for all DMs or selected keywords.',icon:MessageCircle},
 {id:'dm_ai_conversation',title:'AI DM Conversation',desc:'Let AI handle natural multi-turn customer conversations.',icon:Bot},
];

export const AutomationBuilder:React.FC=()=>{
 const{workspaceId,isBuilderOpen,setIsBuilderOpen,editingAutomation,setEditingAutomation,automations,createAutomation,updateAutomation}=useApp();
 const[catalogId,setCatalogId]=useState('');
 const catalogData=useCatalogs(workspaceId);
 const catalogError=catalogId?catalogProblem(catalogData.catalogs.find(c=>c.id===catalogId),catalogData.products.filter(p=>(p.catalog_id||'default')===catalogId)):'';
 const[step,setStep]=useState(1); const[name,setName]=useState(''); const[type,setType]=useState<TriggerType|null>(null);
 const[mode,setMode]=useState<'all'|'keywords'>('all'); const[keywords,setKeywords]=useState<string[]>([]); const[kw,setKw]=useState('');
 const[message,setMessage]=useState(''); const[buttons,setButtons]=useState<{label:string;url:string}[]>([]);
 const[media,setMedia]=useState<Media[]>([]); const[mediaId,setMediaId]=useState(''); const[mediaLoading,setMediaLoading]=useState(false); const[mediaError,setMediaError]=useState('');
 const[aiPrompt,setAiPrompt]=useState('You are a helpful Instagram assistant. Answer naturally, briefly and only about the business.'); const[showSheetPreview,setShowSheetPreview]=useState(false);
 const[fallback,setFallback]=useState("Thanks for your message! Our team will get back to you shortly.");
 const[language,setLanguage]=useState(()=>readBuilderPreference('autoreply_default_ai_language','Auto detect')); const[tone,setTone]=useState(()=>readBuilderPreference('autoreply_default_ai_tone','Friendly')); const[handoff,setHandoff]=useState(true); const[advanced,setAdvanced]=useState(false);
 const[delaySeconds,setDelaySeconds]=useState(0); const[tagName,setTagName]=useState(''); const[autoLikeComment,setAutoLikeComment]=useState(false);
 const[testMessage,setTestMessage]=useState(''); const[testError,setTestError]=useState(''); const[testInput,setTestInput]=useState(''); const[testReply,setTestReply]=useState(''); const[testing,setTesting]=useState(false); const[error,setError]=useState('');
 const sheetCheck=useRef(0);
 const[builderId,setBuilderId]=useState('');
 const[sheetsConnected,setSheetsConnected]=useState(false); const[sheetsEmail,setSheetsEmail]=useState(''); const[sheetsLoading,setSheetsLoading]=useState(false); const[sheetMode,setSheetMode]=useState<'auto'|'manual'>('auto'); const[sheetFields,setSheetFields]=useState<string[]>(['Name','Phone','Product','City','Date','Time']); const[newSheetField,setNewSheetField]=useState(''); const[sheetUrl,setSheetUrl]=useState('');

 useEffect(()=>{sheetCheck.current++;if(!isBuilderOpen)return;
 const query=new URLSearchParams(window.location.search);
 if(query.get('resume')==='ai-sheets'){
  let saved:any=null;try{saved=JSON.parse(sessionStorage.getItem('autoreply:sheets-resume')||'null');}catch{}
  if(saved){setCatalogId(saved.catalogId||'');setBuilderId(saved.builderId || saved.editingId || 'auto_'+crypto.randomUUID());setSheetUrl('');setName(saved.name||'');setType(saved.type||'dm_ai_conversation');setAiPrompt(saved.aiPrompt||'');setTone(saved.tone||'Friendly');setLanguage(saved.language||'Auto detect');setFallback(saved.fallback||"Thanks for your message! Our team will get back to you shortly.");setHandoff(saved.handoff!==false);if(Array.isArray(saved.sheetFields))setSheetFields(saved.sheetFields);setStep(3);setError(query.get('sheets')==='error'?(query.get('message')||'Google Sheets connection failed. Please try again.'):'');setAdvanced(false);}
  sessionStorage.removeItem('autoreply:sheets-resume');query.delete('sheets');query.delete('resume');query.delete('message');const qs=query.toString();window.history.replaceState({},'',window.location.pathname+(qs?'?'+qs:'')+window.location.hash);
  if(saved)return;
 }
 setCatalogId(editingAutomation?.actions.find(a=>a.type===(editingAutomation.trigger_type==='dm_ai_conversation'?'ai_chatbot':'send_dm'))?.catalog_id||'');
 setBuilderId(editingAutomation?.id || 'auto_'+crypto.randomUUID());setSheetUrl('');setSheetFields(editingAutomation?.trigger_config.sheet_fields || ['Name','Phone','Product','City','Date','Time']);setSheetsConnected(false);
 setTestInput('');setTestReply('');setTestMessage('');setTestError('');setStep(1);setError('');setMediaError('');if(editingAutomation){setName(editingAutomation.name);setType(editingAutomation.trigger_type);setMode(editingAutomation.trigger_config.all_or_keywords==='keywords'?'keywords':'all');setKeywords(editingAutomation.trigger_config.keywords||[]);setMediaId(editingAutomation.trigger_config.selected_media_id||'');const dm=editingAutomation.actions.find(a=>a.type==='send_dm');const ai=editingAutomation.actions.find(a=>a.type==='ai_chatbot');setMessage(dm?.message_text||'');setButtons(dm?.buttons||[]);setFallback(dm?.message_text||fallback);setAiPrompt(ai?.ai_system_instruction||aiPrompt);setDelaySeconds(Number(editingAutomation.actions.find(a=>a.type==='add_delay')?.delay_seconds||0));setTagName(editingAutomation.actions.find(a=>a.type==='add_tag')?.tag_name||'');setAutoLikeComment(Boolean(editingAutomation.actions.some(a=>a.type==='auto_like_comment')));}else{setName('');setType(null);setMode('all');setKeywords([]);setMessage('');setButtons([]);setMediaId('');setAdvanced(false);setDelaySeconds(0);setTagName('');setAutoLikeComment(false);setLanguage(readBuilderPreference('autoreply_default_ai_language','Auto detect'));setTone(readBuilderPreference('autoreply_default_ai_tone','Friendly'));const prefillCatalog=sessionStorage.getItem('autoreply:prefill-catalog');if(prefillCatalog){setCatalogId(prefillCatalog);setType('dm_ai_conversation');sessionStorage.removeItem('autoreply:prefill-catalog');}const prefill=sessionStorage.getItem('autoreply:prefill-ai-prompt');const prefillFields=sessionStorage.getItem('autoreply:prefill-sheet-fields');if(prefill){setType('dm_ai_conversation');setAiPrompt(prefill);setAdvanced(true);sessionStorage.removeItem('autoreply:prefill-ai-prompt');}if(prefillFields){try{const parsed=JSON.parse(prefillFields);if(Array.isArray(parsed)&&parsed.length)setSheetFields(parsed.map(String));}catch{}sessionStorage.removeItem('autoreply:prefill-sheet-fields');}}},[isBuilderOpen,editingAutomation]);

 useEffect(()=>{if(isBuilderOpen)return;const q=new URLSearchParams(window.location.search);if(q.get('resume')!=='ai-sheets')return;let saved:any=null;try{saved=JSON.parse(sessionStorage.getItem('autoreply:sheets-resume')||'null')}catch{}if(saved?.editingId)setEditingAutomation(automations.find(a=>a.id===saved.editingId)||null);setIsBuilderOpen(true)},[isBuilderOpen,setIsBuilderOpen,setEditingAutomation,automations]);
 useEffect(()=>{if(!isBuilderOpen||!(type==='comment'||type==='story_reply'))return;void loadMedia();},[type,isBuilderOpen]);
 const loadMedia=async()=>{setMediaLoading(true);setMediaError('');try{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();const kind=type==='story_reply'?'story':'comment';const r=await fetch('/api/instagram/media?kind='+kind,{credentials:'same-origin',headers:token?{'X-Autoreply-Workspace':workspaceId,Authorization:`Bearer ${token}`}:{}});const p=await r.json();if(!r.ok||!p?.ok)throw new Error(p?.error||'Could not load Instagram content.');setMedia(Array.isArray(p.items)?p.items:[]);}catch(e:any){setMedia([]);setMediaError(e?.message||'Could not load Instagram content.');}finally{setMediaLoading(false)}};
 const checkSheets=async()=>{if(!builderId)return;const request=++sheetCheck.current;setSheetsLoading(true);try{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();if(!token)return;const r=await fetch('/api/google-sheets/status?automationId='+encodeURIComponent(builderId),{headers:{'X-Autoreply-Workspace':workspaceId,Authorization:'Bearer '+token}});const p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'Could not check Google Sheets connection.');if(request!==sheetCheck.current)return;setSheetsConnected(Boolean(p?.connected));setSheetsEmail(String(p?.email||''));if(p?.spreadsheetUrl)setSheetUrl(String(p.spreadsheetUrl));if(Array.isArray(p?.fields)&&p.fields.length)setSheetFields(p.fields);}catch(e:any){if(request===sheetCheck.current){setSheetsConnected(false);setError(e?.message||'Could not check Google Sheets connection.')}}finally{if(request===sheetCheck.current)setSheetsLoading(false)}};
 const connectSheets=async()=>{setSheetsLoading(true);setError('');try{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();if(!token)throw new Error('Sign in before connecting Google Sheets.');const r=await fetch('/api/google-sheets/connect?format=json',{headers:{'X-Autoreply-Workspace':workspaceId,Authorization:'Bearer '+token}});const p=await r.json().catch(()=>null);if(!r.ok||!p?.url)throw new Error(p?.error||`Could not start Google Sheets connection (HTTP ${r.status}). Please retry.`);sessionStorage.setItem('autoreply:sheets-resume',JSON.stringify({name,type,aiPrompt,tone,language,fallback,handoff,sheetFields,builderId,catalogId,step:3,editingId:editingAutomation?.id||''}));window.location.assign(p.url)}catch(e:any){setError(e?.message||'Could not start Google Sheets connection.');setSheetsLoading(false)}};
 useEffect(()=>{if(isBuilderOpen&&type==='dm_ai_conversation'&&step===3)void checkSheets()},[isBuilderOpen,type,step,builderId,workspaceId]);
 const detectFields=()=>{if(sheetUrl)return;const p=aiPrompt.toLowerCase();const rules:[string,string[]][]=[['Name',['name','नाम']],['Phone',['phone','mobile','number','फोन','मोबाइल']],['Email',['email','ईमेल']],['City',['city','location','शहर']],['Address',['address','पता']],['Product',['product','item','प्रोडक्ट']],['Quantity',['quantity','qty','क्वांटिटी']],['Date',['date','तारीख']],['Time',['time','समय']],['Weight',['weight','वजन']],['Budget',['budget','बजट']]];const found=rules.filter(([,keys])=>keys.some(k=>p.includes(k))).map(([x])=>x);const next=found.length?found:['Name','Phone'];setSheetFields(next);setShowSheetPreview(true);};
 const createSheet=async()=>{if(sheetsLoading)return null;setSheetsLoading(true);setError('');try{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();if(!token)throw new Error('Sign in first.');const r=await fetch('/api/google-sheets/create-sheet',{method:'POST',headers:{'X-Autoreply-Workspace':workspaceId,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({automationId:builderId,title:(name||'AutoReply')+' AI Leads',fields:sheetFields})});const p=await r.json();if(!r.ok||!p?.ok)throw new Error(p?.error||'Could not create Google Sheet.');setSheetUrl(p.spreadsheetUrl||'');if(p.fields)setSheetFields(p.fields);return p;}catch(e:any){setError(e?.message||'Could not create Google Sheet.');return null}finally{setSheetsLoading(false)}};
 const addSheetField=()=>{const v=newSheetField.trim();if(v&&!sheetFields.some(x=>x.toLowerCase()===v.toLowerCase()))setSheetFields([...sheetFields,v]);setNewSheetField('')};
 useEffect(()=>{
  if(!isBuilderOpen)return;
  const previous=document.activeElement as HTMLElement|null;
  const dialog=document.getElementById('automation-builder-dialog');
  dialog?.querySelector<HTMLButtonElement>('button')?.focus();
  const onKey=(event:KeyboardEvent)=>{
    if(event.key==='Escape')setIsBuilderOpen(false);
    if(event.key!=='Tab'||!dialog)return;
    const items=Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea,select,a[href]')).filter(el=>el.getClientRects().length>0);
    const first=items[0],last=items[items.length-1];
    if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}
    else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}
  };
  document.addEventListener('keydown',onKey);
  return ()=>{document.removeEventListener('keydown',onKey);previous?.focus();};
 },[isBuilderOpen]);
 const selected=useMemo(()=>media.find(x=>x.id===mediaId),[media,mediaId]);
 if(!isBuilderOpen)return null;

 const next=async()=>{setError('');if(step===3&&catalogId&&catalogError)return setError(catalogError);if(step===2&&!name.trim())return setError('Enter an automation name to continue.');if(step===2&&automations.some(a=>a.id!==editingAutomation?.id&&a.name.trim().toLowerCase()===name.trim().toLowerCase()))return setError('Choose a different name. This automation name is already in use.');if(step===1&&!type)return setError('Choose one automation type to continue.');if(step===3&&(type==='comment'||type==='story_reply')&&!mediaId)return setError(type==='comment'?'Select a post or reel first.':'Select an active story first.');if(step===3&&type==='dm_ai_conversation'&&!aiPrompt.trim())return setError('Describe what your AI assistant should do.');if(step===3&&type!=='dm_ai_conversation'&&mode==='keywords'&&!keywords.length)return setError('Add at least one keyword.');if(step===3&&type!=='dm_ai_conversation'&&!(type==='dm'&&catalogId)&&!message.trim())return setError('Write the message that should be sent.');if(step===3&&type==='dm_ai_conversation'&&sheetsConnected&&!sheetUrl){if(!await createSheet())return;}setStep(Math.min(4,step+1));};
 const addKeyword=()=>{const v=kw.trim().toUpperCase();if(v&&!keywords.includes(v))setKeywords([...keywords,v]);setKw('')};
 const addButton=()=>{if(buttons.length<3)setButtons([...buttons,{label:'Visit website',url:'https://'}])};
 const save=async(status:'active'|'paused')=>{if(sheetsLoading)return;setError('');if(catalogId&&catalogError)return setError(catalogError);if(!name.trim()||!type)return setError('Add a name and choose an automation type.');if(type==='dm_ai_conversation'&&!aiPrompt.trim())return setError('Add AI instructions before saving.');const duplicate=automations.some(a=>a.id!==editingAutomation?.id&&a.name.trim().toLowerCase()===name.trim().toLowerCase());if(duplicate)return setError('This automation name is already in use.');if(!type)return;if(type==='dm_ai_conversation'&&sheetsConnected&&!sheetUrl){if(!await createSheet())return;}
  const tc:TriggerConfig={...(type==='dm_ai_conversation'?{sheet_fields:sheetFields}:{}),all_or_keywords:type==='dm_ai_conversation'?'ai_conversation':mode,keywords:mode==='keywords'?keywords:[],smart_matching:true,...((type==='comment'||type==='story_reply')&&selected?{media_scope:'specific_media',selected_media_id:selected.id,selected_media_type:selected.content_type||selected.media_type||'',selected_media_permalink:selected.permalink||'',selected_media_thumbnail_url:selected.thumbnail_url||selected.media_url||'',selected_media_caption:selected.caption||'',...(type==='comment'?{post_scope:'specific_post',specific_post_url:selected.permalink||''}:{story_scope:'specific_story'})}:{})};
  const actions:ActionItem[]=type==='dm_ai_conversation'?[{id:`ai_${Date.now()}`,type:'ai_chatbot',...(catalogId?{catalog_id:catalogId}:{}),ai_model:'gpt-4o-mini',ai_system_instruction:`${aiPrompt}\nTone: ${tone}. Language: ${language}. Human handoff: ${handoff?'enabled':'disabled'}.`},{id:`fallback_${Date.now()}`,type:'send_dm',message_text:fallback}]:[{id:`dm_${Date.now()}`,type:'send_dm',message_text:message,buttons,...(type==='dm'&&catalogId?{catalog_id:catalogId}:{})}];
  if(delaySeconds>0)actions.unshift({id:`delay_${Date.now()}`,type:'add_delay',delay_seconds:Math.min(20,Math.max(1,delaySeconds))});
  if(type==='comment')actions.unshift({id:`comment_${Date.now()}`,type:'reply_comment',comment_reply_text:'Sent you a DM 📩'});
  if(tagName.trim())actions.push({id:`tag_${Date.now()}`,type:'add_tag',tag_name:tagName.trim()});
  const data={id:builderId,name:name.trim(),trigger_type:type,trigger_config:tc,actions,status} as Omit<Automation,'id'|'created_at'|'updated_at'|'stats'>;
  editingAutomation&&automations.some(a=>a.id===editingAutomation.id)?updateAutomation(editingAutomation.id,data):createAutomation(data);setIsBuilderOpen(false);
 };
 const testAI=async()=>{if(!testInput.trim()||testing||!aiPrompt.trim())return;setTestMessage(testInput.trim());setTestError('');setTesting(true);setTestReply('');try{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();const r=await fetch('/api/openai/chat',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},credentials:'same-origin',body:JSON.stringify({text:testInput,history:[],systemInstruction:aiPrompt+(catalogId?'\nApproved product catalog: '+JSON.stringify(catalogData.products.filter(p=>(p.catalog_id||'default')===catalogId&&p.active).map(p=>({name:p.name,price:p.price,description:p.description}))):''),personality:tone,language,maxReplyLength:'Short'})});const p=await r.json();if(!r.ok||!p?.ok)throw new Error(p?.error||'AI test failed');setTestReply(p.reply||'');}catch(e:any){setTestError(e?.message||'AI test failed. Please try again.');}finally{setTesting(false)}};

 return <div id="automation-builder-dialog" role="dialog" aria-modal="true" aria-label="Automation builder" className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-0 backdrop-blur-sm sm:p-5">
  <div className="mx-auto min-h-screen max-w-6xl bg-[#F8FAFD] sm:min-h-0 sm:rounded-[24px] sm:border sm:border-slate-200 sm:shadow-2xl">
   <header className="sticky top-0 z-20 flex items-center justify-between border-b border-slate-200 bg-white/95 px-4 py-3 backdrop-blur sm:rounded-t-[24px] sm:px-6"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Automation Builder</p><h2 className="text-base font-bold text-slate-950">{editingAutomation?'Edit automation':'Create automation'}</h2></div><button aria-label="Close automation builder" onClick={()=>setIsBuilderOpen(false)} className="flex h-9 w-9 items-center justify-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50"><X className="h-4 w-4"/></button></header>
   <div className="border-b border-slate-200 bg-white px-4 py-4 sm:px-6"><div className="mx-auto flex max-w-3xl items-center">{['Type','Name','Setup','Review'].map((x,i)=><React.Fragment key={x}><div className="flex items-center gap-2"><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${step>i+1?'bg-emerald-600 text-white':step===i+1?'bg-indigo-600 text-white':'bg-slate-100 text-slate-400'}`}>{step>i+1?<Check className="h-3.5 w-3.5"/>:i+1}</span><span className={`hidden text-xs font-bold sm:block ${step===i+1?'text-slate-900':'text-slate-400'}`}>{x}</span></div>{i<3&&<div className="mx-2 h-px flex-1 bg-slate-200 sm:mx-4"/>}</React.Fragment>)}</div></div>
   <main className="mx-auto max-w-6xl p-4 sm:p-7">
    {step===2&&<Panel eyebrow="Step 2 of 4" title="Name your automation" desc="Use a clear name so you can recognize this workflow later."><label className="text-xs font-bold text-slate-700">Automation name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Example: Product enquiry reply" className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-900 outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"/><p className="mt-2 text-xs text-slate-400">Only you will see this name in your workspace.</p></Panel>}
    {step===1&&<Panel eyebrow="Step 1 of 4" title="What should start this automation?" desc="Choose one. We will only show the settings relevant to that workflow."><div className="grid gap-3 sm:grid-cols-2">{kinds.map(k=>{const Icon=k.icon;const on=type===k.id;return <button key={k.id} aria-pressed={on} onClick={()=>{setType(k.id);if(k.id!=='dm'&&k.id!=='dm_ai_conversation')setCatalogId('');if(!name.trim())setName(uniqueAutomationName(k.title,automations));}} className={`rounded-[18px] border p-4 text-left transition ${on?'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-100':'border-slate-200 bg-white hover:border-indigo-200'}`}><div className="flex items-start gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${on?'bg-indigo-600 text-white':'bg-slate-50 text-slate-600'}`}><Icon className="h-5 w-5"/></span><div><h3 className="text-sm font-bold text-slate-900">{k.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{k.desc}</p></div></div></button>})}</div></Panel>}
    {step===3&&type!=='dm_ai_conversation'&&<Panel eyebrow="Step 3 of 4" title={type==='comment'?'Choose content & reply':type==='story_reply'?'Choose story & reply':'Set up your DM reply'} desc="Keep the setup simple. Advanced controls can be added later without changing this basic flow.">
      <div className="mb-5"><label className="text-xs font-bold text-slate-700">When should it reply?</label><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>setMode('all')} className={`rounded-xl border p-3 text-left text-xs font-bold ${mode==='all'?'border-indigo-500 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-600'}`}>All messages</button><button onClick={()=>setMode('keywords')} className={`rounded-xl border p-3 text-left text-xs font-bold ${mode==='keywords'?'border-indigo-500 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-600'}`}>Specific keywords</button></div></div>
      {mode==='keywords'&&<div className="mb-5"><label className="text-xs font-bold text-slate-700">Keywords</label><div className="mt-2 flex gap-2"><input value={kw} onChange={e=>setKw(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addKeyword()}}} placeholder="PRICE" className="h-11 flex-1 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-indigo-400"/><button onClick={addKeyword} className="rounded-xl bg-slate-900 px-4 text-xs font-bold text-white">Add</button></div><div className="mt-2 flex flex-wrap gap-2">{keywords.map(k=><span key={k} className="inline-flex items-center gap-1 rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-700">{k}<button onClick={()=>setKeywords(keywords.filter(x=>x!==k))}><X className="h-3 w-3"/></button></span>)}</div></div>}
      <label className="text-xs font-bold text-slate-700">Message to send</label><textarea disabled={type==='dm'&&Boolean(catalogId)} value={message} onChange={e=>setMessage(e.target.value)} rows={4} placeholder="Write the reply your customer should receive…" className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"/>
      <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-800">Link buttons</p><p className="mt-0.5 text-xs text-slate-500">Optional CTA details saved with this automation.</p></div><button onClick={addButton} disabled={buttons.length>=3} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-indigo-700 disabled:opacity-40"><Plus className="h-3.5 w-3.5"/>Add</button></div>{buttons.map((b,i)=><div key={i} className="mt-3 grid gap-2 sm:grid-cols-[.7fr_1.3fr_auto]"><input value={b.label} onChange={e=>setButtons(buttons.map((x,j)=>j===i?{...x,label:e.target.value}:x))} placeholder="Button label" className="h-10 rounded-lg border border-slate-200 px-3 text-xs"/><input value={b.url} onChange={e=>setButtons(buttons.map((x,j)=>j===i?{...x,url:e.target.value}:x))} placeholder="https://…" className="h-10 rounded-lg border border-slate-200 px-3 text-xs"/><button onClick={()=>setButtons(buttons.filter((_,j)=>j!==i))} className="flex h-10 w-10 items-center justify-center rounded-lg border border-rose-100 bg-white text-rose-500" aria-label="Remove link button"><Trash2 className="h-4 w-4"/></button></div>)}</div>
      <div className="mt-5 rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-slate-800">Advanced actions</p><p className="mt-0.5 text-xs text-slate-500">Replies send immediately by default. An optional delay adds up to 20 seconds.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label><span className="text-xs font-bold text-slate-600">Delay before reply (seconds)</span><input type="number" min={0} max={20} value={delaySeconds} onChange={e=>setDelaySeconds(Math.min(20,Math.max(0,Number(e.target.value)||0)))} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-xs"/></label><label><span className="text-xs font-bold text-slate-600">Add contact tag</span><input value={tagName} onChange={e=>setTagName(e.target.value)} placeholder="Example: price-lead" className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-xs"/></label></div></div>
      {(type==='comment'||type==='story_reply')&&<div className="mt-5 border-t border-slate-100 pt-5"><div className="flex items-center justify-between"><label className="text-xs font-bold text-slate-700">{type==='comment'?'Select a post or reel':'Select an active story'}</label><button onClick={loadMedia} className="text-xs font-bold text-indigo-600">Refresh</button></div>{mediaLoading?<div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><LoaderCircle className="h-4 w-4 animate-spin"/>Loading Instagram content…</div>:<div className="mt-3 grid max-h-64 grid-cols-2 gap-2 overflow-y-auto sm:grid-cols-4">{media.map(m=><button key={m.id} onClick={()=>setMediaId(m.id)} className={`overflow-hidden rounded-xl border bg-white text-left ${mediaId===m.id?'border-indigo-500 ring-2 ring-indigo-100':'border-slate-200'}`}><div className="aspect-square bg-slate-100">{m.thumbnail_url||m.media_url?<img src={m.thumbnail_url||m.media_url} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center"><ImageIcon className="h-5 w-5 text-slate-300"/></div>}</div><p className="truncate p-2 text-xs font-semibold text-slate-600">{m.caption||m.content_type||'Instagram content'}</p></button>)}</div>}{mediaError&&<p className="mt-2 text-xs font-semibold text-rose-600">{mediaError}</p>}</div>}
    </Panel>}
    {step===3&&type==='dm_ai_conversation'&&<AiAssistantSetup
      prompt={aiPrompt} onPromptChange={value=>{setAiPrompt(value);setTestReply('');setTestMessage('');setTestError('');}}
      testInput={testInput} onTestInputChange={setTestInput} testMessage={testMessage} testReply={testReply} testError={testError} testing={testing} onTest={testAI}
      sheetsConnected={sheetsConnected} sheetsEmail={sheetsEmail} sheetsLoading={sheetsLoading} onConnectSheets={connectSheets}
      promptTools={<SmartPromptAnalyzer currentPrompt={aiPrompt} onApplyStructuredPrompt={value=>{setAiPrompt(value);setTestReply('');setTestMessage('');}} onAnalysisComplete={r=>{if(r.customer_data_fields?.length)setSheetFields(r.customer_data_fields);}}/>}
      sheetControls={<div className="mt-4 overflow-hidden rounded-2xl border border-blue-100 bg-blue-50/40"><div className="flex items-center justify-between gap-3 border-b border-blue-100 bg-white px-4 py-3"><div><p className="text-xs font-bold text-slate-900">Customer data sheet</p><p className="mt-1 text-xs text-slate-500">Every new AI automation gets its own sheet. Edits keep this sheet.</p></div>{sheetUrl&&<a href={sheetUrl} target="_blank" rel="noreferrer" className="text-xs font-bold text-blue-600">Open Sheet ↗</a>}</div><div className="p-4"><div className="flex flex-wrap gap-2">{sheetFields.map(x=><span key={x} className="inline-flex items-center gap-1 rounded-lg bg-white px-2.5 py-1.5 text-xs font-bold text-slate-700 ring-1 ring-slate-200">{x}<button disabled={Boolean(sheetUrl)} aria-label={"Remove "+x+" column"} onClick={()=>setSheetFields(sheetFields.filter(y=>y!==x))}><X className="h-3 w-3 text-slate-400"/></button></span>)}</div><div className="mt-3 flex gap-2"><input value={newSheetField} onChange={e=>setNewSheetField(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSheetField()}}} disabled={Boolean(sheetUrl)} aria-label="New sheet column" placeholder="Add a field, e.g. Quantity" className="h-10 flex-1 rounded-xl border border-slate-200 bg-white px-3 text-xs outline-none"/><button disabled={Boolean(sheetUrl)} onClick={addSheetField} className="rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-700">Add</button></div><div className="mt-4 overflow-x-auto rounded-xl border border-slate-200 bg-white"><div className="flex min-w-max">{[...sheetFields,'Instagram Username','Created At'].map((x,i)=><div key={x} className="min-w-32 border-r border-slate-200 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-700">{String.fromCharCode(65+i)} · {x}</div>)}</div><div className="flex min-w-max">{[...sheetFields,'Instagram Username','Created At'].map(x=><div key={x} className="min-w-32 border-r border-t border-slate-100 px-3 py-3 text-xs text-slate-400">Column preview</div>)}</div></div><button onClick={createSheet} disabled={sheetsLoading||!sheetFields.length||Boolean(sheetUrl)} className="mt-3 h-10 w-full rounded-xl bg-blue-600 text-xs font-bold text-white disabled:opacity-50">{sheetsLoading?'Creating…':sheetUrl?'Sheet ready for this automation':'Create Google Sheet'}</button></div></div>}
      replySettings={<div>      <button aria-expanded={advanced} aria-controls="ai-reply-settings" onClick={()=>setAdvanced(!advanced)} className="mt-4 flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white p-4 text-left"><div><p className="text-xs font-bold text-slate-800">Optional reply settings</p><p className="mt-0.5 text-xs text-slate-500">Tone, language, fallback message and human handoff.</p></div><ChevronRight className={`h-4 w-4 text-slate-400 transition ${advanced?'rotate-90':''}`}/></button>
      {advanced&&<div id="ai-reply-settings" className="mt-3 grid gap-4 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2"><div><label htmlFor="ai-tone" className="text-xs font-bold text-slate-600">Tone</label><select id="ai-tone" value={tone} onChange={e=>setTone(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-2 text-xs"><option>Friendly</option><option>Professional</option><option>Sales Expert</option><option>Customer Support</option></select></div><div><label htmlFor="ai-language" className="text-xs font-bold text-slate-600">Language</label><select id="ai-language" value={language} onChange={e=>setLanguage(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-2 text-xs"><option>Auto detect</option><option>English</option><option>Hindi</option><option>Hinglish</option></select></div><div className="sm:col-span-2"><label htmlFor="ai-fallback" className="text-xs font-bold text-slate-600">Fallback message</label><input id="ai-fallback" value={fallback} onChange={e=>setFallback(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-xs"/></div><label className="flex items-center gap-2 text-xs font-semibold text-slate-700 sm:col-span-2"><input type="checkbox" checked={handoff} onChange={e=>setHandoff(e.target.checked)}/>Allow human handoff</label></div>}
</div>}
    />}
    {step===3&&(type==='dm'||type==='dm_ai_conversation')&&<CatalogPicker value={catalogId} onChange={setCatalogId} ai={type==='dm_ai_conversation'}/>}
    {step===4&&catalogId&&<CatalogPicker value={catalogId} onChange={setCatalogId} ai={type==='dm_ai_conversation'} readOnly/>}
    {step===4&&<Panel eyebrow="Step 4 of 4" title="Review & publish" desc="Check the essentials before turning this automation on."><div className={type==='dm_ai_conversation'?'':'grid min-w-0 gap-6 lg:grid-cols-[minmax(0,1fr)_360px]'}><div className="min-w-0"><div className="divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white">{[['Name',name],['Type',kinds.find(k=>k.id===type)?.title||'—'],['Trigger',type==='dm_ai_conversation'?'AI conversation':mode==='all'?'All messages':keywords.join(', ')||'No keywords'],['Extra actions',[delaySeconds>0?delaySeconds+'s delay':'',tagName.trim()?'tag: '+tagName.trim():'',type==='comment'&&autoLikeComment?'auto-like comment':''].filter(Boolean).join(' · ')||'None'],...((type==='comment'||type==='story_reply')?[['Content',selected?.caption||selected?.content_type||'Selected Instagram content']]:[])].map(([a,b])=><div key={a} className="flex gap-4 px-4 py-3"><span className="w-24 shrink-0 text-xs font-bold text-slate-400">{a}</span><span className="text-xs font-semibold text-slate-800">{b}</span></div>)}</div>{type==='dm_ai_conversation'&&<div className="mt-4 rounded-xl border border-slate-200 bg-white p-4"><p className="text-sm font-semibold text-slate-900">{type==='dm_ai_conversation'?'AI instructions':'Customer reply preview'}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{type==='dm_ai_conversation'?aiPrompt:message}</p>{type==='dm_ai_conversation'&&<p className="mt-3 text-sm text-indigo-700">Test your assistant in the Setup step before publishing. AI answers depend on the customer’s message.</p>}</div>}<div className="mt-4 rounded-xl bg-indigo-50 p-3 text-xs font-semibold text-emerald-800">Review your automation before publishing. Publish to turn it on, or save a paused draft to finish later.</div></div>{(type==='dm'||type==='comment'||type==='story_reply')&&!catalogId&&<AutomationReviewPhone type={type} message={message} buttons={buttons} mode={mode} keywords={keywords} media={selected}/>}</div></Panel>}
    {error&&<p role="alert" className="mt-4 rounded-xl border border-rose-100 bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</p>}
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-5"><button onClick={()=>step===1?setIsBuilderOpen(false):setStep(step-1)} className="inline-flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>{step===1?'Cancel':'Back'}</button>{step<4?<div className="flex flex-wrap justify-end gap-2">{step===3&&type==='dm_ai_conversation'&&<button disabled={sheetsLoading} onClick={()=>save('paused')} className="h-11 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700">Save draft</button>}<button disabled={sheetsLoading} onClick={next} className="inline-flex h-11 items-center gap-2 rounded-xl bg-indigo-600 px-5 text-xs font-bold text-white shadow-sm hover:bg-indigo-700">{step===3?'Continue to review':'Continue'}<ChevronRight className="h-4 w-4"/></button></div>:<div className="flex gap-2"><button disabled={sheetsLoading} onClick={()=>save('paused')} className="h-11 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-700">Save draft</button><button disabled={sheetsLoading} onClick={()=>save('active')} className="inline-flex h-11 items-center gap-2 rounded-xl bg-indigo-600 px-5 text-xs font-bold text-white"><Zap className="h-4 w-4"/>Publish automation</button></div>}</div>
   </main>
  </div>
 </div>;
};
const Panel=({eyebrow,title,desc,children}:{eyebrow:string;title:string;desc:string;children:React.ReactNode})=><section className="rounded-[20px] border border-slate-200 bg-white p-5 shadow-[0_6px_22px_rgba(15,23,42,.035)] sm:p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-indigo-600">{eyebrow}</p><h2 className="mt-1 text-xl font-bold tracking-tight text-slate-950">{title}</h2><p className="mt-1 mb-6 text-xs leading-5 text-slate-500">{desc}</p>{children}</section>;


