import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,Bot,Check,ChevronRight,Clock,Image as ImageIcon,Instagram,LoaderCircle,MessageCircle,MessageSquare,Plus,Send,Sparkles,Trash2,X,Zap}from'lucide-react';
import{useApp}from'../../context/AppContext';
import{ActionItem,Automation,TriggerConfig,TriggerType}from'../../types';

type Media={id:string;content_type?:string;media_type?:string;caption?:string;media_url?:string;thumbnail_url?:string;permalink?:string};
const kinds:{id:TriggerType;title:string;desc:string;icon:any}[]=[
 {id:'comment',title:'Comment Automation',desc:'Reply to comments on a selected post or reel.',icon:MessageSquare},
 {id:'story_reply',title:'Story Reply',desc:'Reply when someone responds to a selected active story.',icon:Instagram},
 {id:'dm',title:'DM Reply',desc:'Send a fixed reply for all DMs or selected keywords.',icon:MessageCircle},
 {id:'dm_ai_conversation',title:'AI DM Conversation',desc:'Let AI handle natural multi-turn customer conversations.',icon:Bot},
];

export const AutomationBuilder:React.FC=()=>{
 const{isBuilderOpen,setIsBuilderOpen,editingAutomation,automations,createAutomation,updateAutomation}=useApp();
 const[step,setStep]=useState(1); const[name,setName]=useState(''); const[type,setType]=useState<TriggerType|null>(null);
 const[mode,setMode]=useState<'all'|'keywords'>('all'); const[keywords,setKeywords]=useState<string[]>([]); const[kw,setKw]=useState('');
 const[message,setMessage]=useState(''); const[buttons,setButtons]=useState<{label:string;url:string}[]>([]);
 const[media,setMedia]=useState<Media[]>([]); const[mediaId,setMediaId]=useState(''); const[mediaLoading,setMediaLoading]=useState(false); const[mediaError,setMediaError]=useState('');
 const[aiPrompt,setAiPrompt]=useState('You are a helpful Instagram assistant. Answer naturally, briefly and only about the business.');
 const[fallback,setFallback]=useState("Thanks for your message! Our team will get back to you shortly.");
 const[language,setLanguage]=useState('Auto detect'); const[tone,setTone]=useState('Friendly'); const[handoff,setHandoff]=useState(true); const[advanced,setAdvanced]=useState(false);
 const[testInput,setTestInput]=useState(''); const[testReply,setTestReply]=useState(''); const[testing,setTesting]=useState(false); const[error,setError]=useState('');
 const[sheetsConnected,setSheetsConnected]=useState(false); const[sheetsEmail,setSheetsEmail]=useState(''); const[sheetsLoading,setSheetsLoading]=useState(false); const[sheetMode,setSheetMode]=useState<'auto'|'manual'>('auto'); const[sheetFields,setSheetFields]=useState<string[]>(['Name','Phone','Product','City','Date','Time']); const[newSheetField,setNewSheetField]=useState(''); const[sheetUrl,setSheetUrl]=useState('');

 useEffect(()=>{if(!isBuilderOpen)return;setStep(1);setError('');setMediaError('');if(editingAutomation){setName(editingAutomation.name);setType(editingAutomation.trigger_type);setMode(editingAutomation.trigger_config.all_or_keywords==='keywords'?'keywords':'all');setKeywords(editingAutomation.trigger_config.keywords||[]);setMediaId(editingAutomation.trigger_config.selected_media_id||'');const dm=editingAutomation.actions.find(a=>a.type==='send_dm');const ai=editingAutomation.actions.find(a=>a.type==='ai_chatbot');setMessage(dm?.message_text||'');setButtons(dm?.buttons||[]);setFallback(dm?.message_text||fallback);setAiPrompt(ai?.ai_system_instruction||aiPrompt);}else{setName('');setType(null);setMode('all');setKeywords([]);setMessage('');setButtons([]);setMediaId('');setAdvanced(false);}},[isBuilderOpen,editingAutomation]);

 useEffect(()=>{if(!isBuilderOpen||!(type==='comment'||type==='story_reply'))return;void loadMedia();},[type,isBuilderOpen]);
 const loadMedia=async()=>{setMediaLoading(true);setMediaError('');try{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();const kind=type==='story_reply'?'story':'comment';const r=await fetch('/api/instagram/media?kind='+kind,{credentials:'same-origin',headers:token?{Authorization:`Bearer ${token}`}:{}});const p=await r.json();if(!r.ok||!p?.ok)throw new Error(p?.error||'Could not load Instagram content.');setMedia(Array.isArray(p.items)?p.items:[]);}catch(e:any){setMedia([]);setMediaError(e?.message||'Could not load Instagram content.');}finally{setMediaLoading(false)}};
 const checkSheets=async()=>{setSheetsLoading(true);try{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();if(!token)return;const r=await fetch('/api/google-sheets/status',{headers:{Authorization:'Bearer '+token}});const p=await r.json();setSheetsConnected(Boolean(p?.connected));setSheetsEmail(String(p?.email||''));}catch{}finally{setSheetsLoading(false)}};
 const connectSheets=async()=>{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();if(!token)return setError('Sign in before connecting Google Sheets.');const r=await fetch('/api/google-sheets/connect',{headers:{Authorization:'Bearer '+token},redirect:'manual'});if(r.status===0)return;const loc=r.headers.get('location');if(loc)window.location.assign(loc);else{const p=await r.json().catch(()=>null);setError(p?.error||'Could not start Google Sheets connection.')}};
 useEffect(()=>{if(isBuilderOpen&&type==='dm_ai_conversation'&&advanced)void checkSheets()},[isBuilderOpen,type,advanced]);
 const detectFields=()=>{const p=aiPrompt.toLowerCase();const rules:[string,string[]][]=[['Name',['name','नाम']],['Phone',['phone','mobile','number','फोन','मोबाइल']],['Email',['email','ईमेल']],['City',['city','location','शहर']],['Address',['address','पता']],['Product',['product','item','प्रोडक्ट']],['Quantity',['quantity','qty','क्वांटिटी']],['Date',['date','तारीख']],['Time',['time','समय']],['Weight',['weight','वजन']],['Budget',['budget','बजट']]];const found=rules.filter(([,keys])=>keys.some(k=>p.includes(k))).map(([x])=>x);setSheetFields(found.length?found:['Name','Phone']);};
 const createSheet=async()=>{setSheetsLoading(true);setError('');try{const token=await(await import('../../lib/supabase')).auth.currentUser?.getIdToken();if(!token)throw new Error('Sign in first.');const r=await fetch('/api/google-sheets/create-sheet',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({title:(name||'AutoReply')+' AI Leads',fields:sheetFields})});const p=await r.json();if(!r.ok||!p?.ok)throw new Error(p?.error||'Could not create Google Sheet.');setSheetUrl(p.spreadsheetUrl||'');}catch(e:any){setError(e?.message||'Could not create Google Sheet.')}finally{setSheetsLoading(false)}};
 const addSheetField=()=>{const v=newSheetField.trim();if(v&&!sheetFields.some(x=>x.toLowerCase()===v.toLowerCase()))setSheetFields([...sheetFields,v]);setNewSheetField('')};
 const selected=useMemo(()=>media.find(x=>x.id===mediaId),[media,mediaId]);
 if(!isBuilderOpen)return null;

 const next=()=>{setError('');if(step===1&&!name.trim())return setError('Enter an automation name to continue.');if(step===2&&!type)return setError('Choose one automation type to continue.');if(step===3&&(type==='comment'||type==='story_reply')&&!mediaId)return setError(type==='comment'?'Select a post or reel first.':'Select an active story first.');if(step===3&&type!=='dm_ai_conversation'&&!message.trim())return setError('Write the message that should be sent.');setStep(Math.min(4,step+1));};
 const addKeyword=()=>{const v=kw.trim().toUpperCase();if(v&&!keywords.includes(v))setKeywords([...keywords,v]);setKw('')};
 const addButton=()=>{if(buttons.length<3)setButtons([...buttons,{label:'Visit website',url:'https://'}])};
 const save=(status:'active'|'paused')=>{const duplicate=automations.some(a=>a.id!==editingAutomation?.id&&a.name.trim().toLowerCase()===name.trim().toLowerCase());if(duplicate)return setError('This automation name is already in use.');if(!type)return;
  const tc:TriggerConfig={all_or_keywords:type==='dm_ai_conversation'?'ai_conversation':mode,keywords:mode==='keywords'?keywords:[],smart_matching:true,...((type==='comment'||type==='story_reply')&&selected?{media_scope:'specific_media',selected_media_id:selected.id,selected_media_type:selected.content_type||selected.media_type||'',selected_media_permalink:selected.permalink||'',selected_media_thumbnail_url:selected.thumbnail_url||selected.media_url||'',selected_media_caption:selected.caption||'',...(type==='comment'?{post_scope:'specific_post',specific_post_url:selected.permalink||''}:{story_scope:'specific_story'})}:{})};
  const actions:ActionItem[]=type==='dm_ai_conversation'?[{id:`ai_${Date.now()}`,type:'ai_chatbot',ai_model:'gpt-4o-mini',ai_system_instruction:`${aiPrompt}\nTone: ${tone}. Language: ${language}. Human handoff: ${handoff?'enabled':'disabled'}.`},{id:`fallback_${Date.now()}`,type:'send_dm',message_text:fallback}]:[{id:`dm_${Date.now()}`,type:'send_dm',message_text:message,buttons}];
  if(type==='comment')actions.unshift({id:`comment_${Date.now()}`,type:'reply_comment',comment_reply_text:'Sent you a DM 📩'});
  const data={name:name.trim(),trigger_type:type,trigger_config:tc,actions,status} as Omit<Automation,'id'|'created_at'|'updated_at'|'stats'>;
  editingAutomation?updateAutomation(editingAutomation.id,data):createAutomation(data);setIsBuilderOpen(false);
 };
 const testAI=async()=>{if(!testInput.trim()||testing)return;setTesting(true);setTestReply('');try{const r=await fetch('/api/openai/chat',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({text:testInput,history:[],systemInstruction:aiPrompt,personality:tone,language,maxReplyLength:'Short'})});const p=await r.json();if(!r.ok||!p?.ok)throw new Error(p?.error||'AI test failed');setTestReply(p.reply||'');}catch(e:any){setTestReply(e?.message||'AI test failed');}finally{setTesting(false)}};

 return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-0 backdrop-blur-sm sm:p-5">
  <div className="mx-auto min-h-screen max-w-5xl bg-[#F8FAFD] sm:min-h-0 sm:rounded-[24px] sm:border sm:border-slate-200 sm:shadow-2xl">
   <header className="sticky top-0 z-20 flex items-center justify-between border-b border-slate-200 bg-white/95 px-4 py-3 backdrop-blur sm:rounded-t-[24px] sm:px-6"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-indigo-600">Automation Builder</p><h2 className="text-base font-bold text-slate-950">{editingAutomation?'Edit automation':'Create automation'}</h2></div><button onClick={()=>setIsBuilderOpen(false)} className="flex h-9 w-9 items-center justify-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50"><X className="h-4 w-4"/></button></header>
   <div className="border-b border-slate-200 bg-white px-4 py-4 sm:px-6"><div className="mx-auto flex max-w-3xl items-center">{['Name','Type','Setup','Review'].map((x,i)=><React.Fragment key={x}><div className="flex items-center gap-2"><span className={`flex h-7 w-7 items-center justify-center rounded-full text-[11px] font-bold ${step>i+1?'bg-emerald-600 text-white':step===i+1?'bg-indigo-600 text-white':'bg-slate-100 text-slate-400'}`}>{step>i+1?<Check className="h-3.5 w-3.5"/>:i+1}</span><span className={`hidden text-xs font-bold sm:block ${step===i+1?'text-slate-900':'text-slate-400'}`}>{x}</span></div>{i<3&&<div className="mx-2 h-px flex-1 bg-slate-200 sm:mx-4"/>}</React.Fragment>)}</div></div>
   <main className="mx-auto max-w-4xl p-4 sm:p-7">
    {step===1&&<Panel eyebrow="Step 1 of 4" title="Name your automation" desc="Use a clear name so you can recognize this workflow later."><label className="text-xs font-bold text-slate-700">Automation name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Example: Product enquiry reply" className="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-900 outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"/><p className="mt-2 text-[11px] text-slate-400">Only you will see this name in your workspace.</p></Panel>}
    {step===2&&<Panel eyebrow="Step 2 of 4" title="What should start this automation?" desc="Choose one. We will only show the settings relevant to that workflow."><div className="grid gap-3 sm:grid-cols-2">{kinds.map(k=>{const Icon=k.icon;const on=type===k.id;return <button key={k.id} onClick={()=>setType(k.id)} className={`rounded-[18px] border p-4 text-left transition ${on?'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-100':'border-slate-200 bg-white hover:border-indigo-200'}`}><div className="flex items-start gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${on?'bg-indigo-600 text-white':'bg-slate-50 text-slate-600'}`}><Icon className="h-5 w-5"/></span><div><h3 className="text-sm font-bold text-slate-900">{k.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{k.desc}</p></div></div></button>})}</div></Panel>}
    {step===3&&type!=='dm_ai_conversation'&&<Panel eyebrow="Step 3 of 4" title={type==='comment'?'Choose content & reply':type==='story_reply'?'Choose story & reply':'Set up your DM reply'} desc="Keep the setup simple. Advanced controls can be added later without changing this basic flow.">
      <div className="mb-5"><label className="text-xs font-bold text-slate-700">When should it reply?</label><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>setMode('all')} className={`rounded-xl border p-3 text-left text-xs font-bold ${mode==='all'?'border-indigo-500 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-600'}`}>All messages</button><button onClick={()=>setMode('keywords')} className={`rounded-xl border p-3 text-left text-xs font-bold ${mode==='keywords'?'border-indigo-500 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-600'}`}>Specific keywords</button></div></div>
      {mode==='keywords'&&<div className="mb-5"><label className="text-xs font-bold text-slate-700">Keywords</label><div className="mt-2 flex gap-2"><input value={kw} onChange={e=>setKw(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addKeyword()}}} placeholder="PRICE" className="h-11 flex-1 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-indigo-400"/><button onClick={addKeyword} className="rounded-xl bg-slate-900 px-4 text-xs font-bold text-white">Add</button></div><div className="mt-2 flex flex-wrap gap-2">{keywords.map(k=><span key={k} className="inline-flex items-center gap-1 rounded-full bg-indigo-50 px-2.5 py-1 text-[11px] font-bold text-indigo-700">{k}<button onClick={()=>setKeywords(keywords.filter(x=>x!==k))}><X className="h-3 w-3"/></button></span>)}</div></div>}
      <label className="text-xs font-bold text-slate-700">Message to send</label><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={4} placeholder="Write the reply your customer should receive…" className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"/>
      <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-800">Link buttons</p><p className="mt-0.5 text-[11px] text-slate-500">Optional CTA details saved with this automation.</p></div><button onClick={addButton} disabled={buttons.length>=3} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-3 py-2 text-[11px] font-bold text-indigo-700 disabled:opacity-40"><Plus className="h-3.5 w-3.5"/>Add</button></div>{buttons.map((b,i)=><div key={i} className="mt-3 grid gap-2 sm:grid-cols-[.7fr_1.3fr_auto]"><input value={b.label} onChange={e=>setButtons(buttons.map((x,j)=>j===i?{...x,label:e.target.value}:x))} placeholder="Button label" className="h-10 rounded-lg border border-slate-200 px-3 text-xs"/><input value={b.url} onChange={e=>setButtons(buttons.map((x,j)=>j===i?{...x,url:e.target.value}:x))} placeholder="https://…" className="h-10 rounded-lg border border-slate-200 px-3 text-xs"/><button onClick={()=>setButtons(buttons.filter((_,j)=>j!==i))} className="flex h-10 w-10 items-center justify-center rounded-lg border border-rose-100 bg-white text-rose-500"><Trash2 className="h-4 w-4"/></button></div>)}</div>
      {(type==='comment'||type==='story_reply')&&<div className="mt-5 border-t border-slate-100 pt-5"><div className="flex items-center justify-between"><label className="text-xs font-bold text-slate-700">{type==='comment'?'Select a post or reel':'Select an active story'}</label><button onClick={loadMedia} className="text-[11px] font-bold text-indigo-600">Refresh</button></div>{mediaLoading?<div className="mt-3 flex items-center gap-2 text-xs text-slate-500"><LoaderCircle className="h-4 w-4 animate-spin"/>Loading Instagram content…</div>:<div className="mt-3 grid max-h-64 grid-cols-2 gap-2 overflow-y-auto sm:grid-cols-4">{media.map(m=><button key={m.id} onClick={()=>setMediaId(m.id)} className={`overflow-hidden rounded-xl border bg-white text-left ${mediaId===m.id?'border-indigo-500 ring-2 ring-indigo-100':'border-slate-200'}`}><div className="aspect-square bg-slate-100">{m.thumbnail_url||m.media_url?<img src={m.thumbnail_url||m.media_url} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center"><ImageIcon className="h-5 w-5 text-slate-300"/></div>}</div><p className="truncate p-2 text-[10px] font-semibold text-slate-600">{m.caption||m.content_type||'Instagram content'}</p></button>)}</div>}{mediaError&&<p className="mt-2 text-xs font-semibold text-rose-600">{mediaError}</p>}</div>}
    </Panel>}
    {step===3&&type==='dm_ai_conversation'&&<Panel eyebrow="Step 3 of 4" title="Set up your AI assistant" desc="Start with the essentials. Advanced settings stay out of the way until you need them.">
      <label className="text-xs font-bold text-slate-700">What should the AI know and do?</label><textarea value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)} rows={7} placeholder="Describe your business, products, FAQs and how the AI should help customers…" className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm leading-6 outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100"/>
      <div className="mt-5 rounded-xl border border-indigo-100 bg-indigo-50/50 p-4"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-indigo-600"/><p className="text-xs font-bold text-slate-800">Test your assistant</p></div><div className="mt-3 flex gap-2"><input value={testInput} onChange={e=>setTestInput(e.target.value)} placeholder="Type a customer message…" className="h-11 flex-1 rounded-xl border border-slate-200 bg-white px-3 text-xs"/><button onClick={testAI} className="rounded-xl bg-indigo-600 px-4 text-xs font-bold text-white">{testing?'Testing…':'Test'}</button></div>{testReply&&<div className="mt-3 rounded-xl bg-white p-3 text-xs leading-5 text-slate-700">{testReply}</div>}</div>
      <button onClick={()=>setAdvanced(!advanced)} className="mt-5 flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white p-4 text-left"><div><p className="text-xs font-bold text-slate-800">Advanced settings</p><p className="mt-0.5 text-[11px] text-slate-500">Tone, language, fallback and human handoff.</p></div><ChevronRight className={`h-4 w-4 text-slate-400 transition ${advanced?'rotate-90':''}`}/></button>
      {advanced&&<div className="mt-3 grid gap-4 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2"><div><label className="text-[11px] font-bold text-slate-600">Tone</label><select value={tone} onChange={e=>setTone(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-2 text-xs"><option>Friendly</option><option>Professional</option><option>Sales Expert</option><option>Customer Support</option></select></div><div><label className="text-[11px] font-bold text-slate-600">Language</label><select value={language} onChange={e=>setLanguage(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-2 text-xs"><option>Auto detect</option><option>English</option><option>Hindi</option><option>Hinglish</option></select></div><div className="sm:col-span-2"><label className="text-[11px] font-bold text-slate-600">Fallback message</label><input value={fallback} onChange={e=>setFallback(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-xs"/></div><label className="flex items-center gap-2 text-xs font-semibold text-slate-700 sm:col-span-2"><input type="checkbox" checked={handoff} onChange={e=>setHandoff(e.target.checked)}/>Allow human handoff</label>
      <div className="sm:col-span-2 rounded-xl border border-emerald-100 bg-emerald-50/40 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold text-slate-900">Google Sheets data collection</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{sheetsConnected?`Connected as ${sheetsEmail||'Google account'}`:'Connect a Google account to save customer details collected by AI.'}</p></div><button onClick={connectSheets} disabled={sheetsLoading} className="h-10 rounded-xl bg-white px-4 text-[11px] font-bold text-emerald-700 shadow-sm ring-1 ring-emerald-200">{sheetsConnected?'Reconnect Google Sheets':'Connect Google Sheets'}</button></div>
      {sheetsConnected&&<><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setSheetMode('auto')} className={`rounded-xl border p-3 text-left text-[11px] font-bold ${sheetMode==='auto'?'border-emerald-500 bg-white text-emerald-700':'border-slate-200 bg-white/60 text-slate-600'}`}>AI Auto Detect<p className="mt-1 font-normal leading-4 text-slate-500">Detect useful customer fields from your AI prompt.</p></button><button onClick={()=>setSheetMode('manual')} className={`rounded-xl border p-3 text-left text-[11px] font-bold ${sheetMode==='manual'?'border-emerald-500 bg-white text-emerald-700':'border-slate-200 bg-white/60 text-slate-600'}`}>Create manually<p className="mt-1 font-normal leading-4 text-slate-500">Choose exactly which fields the AI should collect.</p></button></div><div className="mt-3"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-bold text-slate-700">Data fields</p>{sheetMode==='auto'&&<button onClick={detectFields} className="text-[10px] font-bold text-emerald-700">Detect from AI prompt</button>}</div><div className="mt-2 flex flex-wrap gap-2">{sheetFields.map(x=><span key={x} className="inline-flex items-center gap-1 rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-slate-600 ring-1 ring-slate-200">{x}<button onClick={()=>setSheetFields(sheetFields.filter(y=>y!==x))}><X className="h-3 w-3"/></button></span>)}</div><div className="mt-3 flex gap-2"><input value={newSheetField} onChange={e=>setNewSheetField(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSheetField()}}} placeholder="Add field, e.g. Weight" className="h-9 flex-1 rounded-lg border border-slate-200 bg-white px-3 text-[11px]"/><button onClick={addSheetField} className="rounded-lg bg-white px-3 text-[10px] font-bold text-slate-700 ring-1 ring-slate-200">Add</button></div><button onClick={createSheet} disabled={sheetsLoading||!sheetFields.length} className="mt-3 h-10 w-full rounded-xl bg-emerald-600 px-4 text-[11px] font-bold text-white disabled:opacity-50">{sheetsLoading?'Creating…':'Create Google Sheet & Columns'}</button>{sheetUrl&&<a href={sheetUrl} target="_blank" rel="noreferrer" className="mt-2 block text-center text-[10px] font-bold text-emerald-700 underline">Open created Google Sheet</a>}<p className="mt-2 text-[10px] leading-4 text-slate-500">AI can fill Date, Time and other fields automatically when that information is available.</p></div></>}</div>
      </div>}
    </Panel>}
    {step===4&&<Panel eyebrow="Step 4 of 4" title="Review & publish" desc="Check the essentials before turning this automation on."><div className="divide-y divide-slate-100 rounded-xl border border-slate-200 bg-white">{[['Name',name],['Type',kinds.find(k=>k.id===type)?.title||'—'],['Trigger',type==='dm_ai_conversation'?'AI conversation':mode==='all'?'All messages':keywords.join(', ')||'No keywords'],...((type==='comment'||type==='story_reply')?[['Content',selected?.caption||selected?.content_type||'Selected Instagram content']]:[])].map(([a,b])=><div key={a} className="flex gap-4 px-4 py-3"><span className="w-24 shrink-0 text-[11px] font-bold text-slate-400">{a}</span><span className="text-xs font-semibold text-slate-800">{b}</span></div>)}</div><div className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-800">Ready to save. You can publish now or keep it paused as a draft.</div></Panel>}
    {error&&<p className="mt-4 rounded-xl border border-rose-100 bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</p>}
    <div className="mt-5 flex items-center justify-between gap-3"><button onClick={()=>step===1?setIsBuilderOpen(false):setStep(step-1)} className="inline-flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>{step===1?'Cancel':'Back'}</button>{step<4?<button onClick={next} className="inline-flex h-11 items-center gap-2 rounded-xl bg-slate-950 px-5 text-xs font-bold text-white shadow-sm hover:bg-slate-800">Next<ChevronRight className="h-4 w-4"/></button>:<div className="flex gap-2"><button onClick={()=>save('paused')} className="h-11 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-700">Save draft</button><button onClick={()=>save('active')} className="inline-flex h-11 items-center gap-2 rounded-xl bg-indigo-600 px-5 text-xs font-bold text-white"><Zap className="h-4 w-4"/>Publish automation</button></div>}</div>
   </main>
  </div>
 </div>;
};
const Panel=({eyebrow,title,desc,children}:{eyebrow:string;title:string;desc:string;children:React.ReactNode})=><section className="rounded-[20px] border border-slate-200 bg-white p-5 shadow-[0_6px_22px_rgba(15,23,42,.035)] sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-indigo-600">{eyebrow}</p><h2 className="mt-1 text-xl font-bold tracking-tight text-slate-950">{title}</h2><p className="mt-1 mb-6 text-xs leading-5 text-slate-500">{desc}</p>{children}</section>;
