import React,{useState} from 'react';
import {customerStages,type CustomerInsight as Insight,type CustomerStage} from '../../lib/customerInsights';
import {useApp} from '../../context/AppContext';
import {supabase} from '../../lib/supabase';
import type {Contact} from '../../types';
export const CustomerBadges=({insight}:{insight?:Insight})=>{const stage=insight?.stage || 'new';return <div className="mt-2 flex flex-wrap gap-1.5"><span title={insight?.reason} className={'rounded-full px-2 py-1 text-[11px] font-bold '+customerStages[stage].color}>{customerStages[stage].label}</span><span className={'rounded-full px-2 py-1 text-[11px] font-bold '+(insight?.priority==='high'?'bg-amber-100 text-amber-800':'bg-slate-100 text-slate-600')}>{insight?.priority==='high'?'High':insight?.priority==='low'?'Low':'Normal'} priority</span></div>};
export const CustomerInsightPanel=({contact}:{contact:Contact})=>{
 const {workspaceId}=useApp();const insight=contact.customer_insight;const [error,setError]=useState('');const [saving,setSaving]=useState(false);
 const update=async(stage:CustomerStage,priority:Insight['priority'],source:Insight['source']='manual')=>{setSaving(true);setError('');try{const {error}=await supabase.rpc('autoreply_save_customer_insight',{p_user_id:workspaceId,p_contact_id:contact.id,p_data:{...insight,stage,priority,source,reason:source==='manual'?'Set by workspace owner':'Automatic assessment resumed',updated_at:new Date().toISOString()}});if(error)throw error;}catch(e:any){setError(e.message||'Could not save customer priority');}finally{setSaving(false)}};
 return <section className="my-4 rounded-xl border border-slate-200 bg-white p-4"><h3 className="text-sm font-bold text-slate-900">Customer insight</h3><CustomerBadges insight={insight}/><p className="mt-2 text-xs text-slate-500">{insight?.source==='manual'?'Manual · preserved until you change it':'Automatic estimate · based on conversation'}</p><p className="mt-2 text-xs text-slate-700">{insight?.reason || 'No clear purchase intent yet'}</p>{insight?.summary&&<p className="mt-2 text-xs text-slate-600">{insight.summary}</p>}{insight?.next_step&&<p className="mt-2 text-xs font-semibold text-indigo-700">Next: {insight.next_step}</p>}
 <div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs text-slate-500">Customer status<select aria-label="Customer status" disabled={saving} value={insight?.stage||'new'} onChange={e=>void update(e.target.value as CustomerStage,insight?.priority||'normal')} className="mt-1 min-h-10 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs">{Object.entries(customerStages).map(([id,item])=><option key={id} value={id}>{item.label}</option>)}</select></label><label className="text-xs text-slate-500">Priority<select aria-label="Customer priority" disabled={saving} value={insight?.priority||'normal'} onChange={e=>void update(insight?.stage||'new',e.target.value as Insight['priority'])} className="mt-1 min-h-10 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs"><option value="high">High</option><option value="normal">Normal</option><option value="low">Low</option></select></label></div>
 {insight?.source==='manual'&&<button disabled={saving} onClick={()=>void update('new','normal','automatic')} className="mt-2 text-xs font-semibold text-indigo-600">Resume automatic assessment</button>}{error&&<p role="alert" className="mt-2 text-xs text-rose-700">{error}</p>}</section>;
};
