-- AutoReply.io admin control center
create table if not exists public.autoreply_plans (
  id text primary key,
  name text not null,
  price_inr integer not null default 0 check (price_inr >= 0),
  total_messages integer not null default 0 check (total_messages >= 0),
  ai_replies integer not null default 0 check (ai_replies >= 0),
  instagram_accounts integer not null default 1 check (instagram_accounts >= 0),
  automations_limit integer null check (automations_limit is null or automations_limit >= 0),
  billing_days integer not null default 30 check (billing_days > 0),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.autoreply_plans
(id,name,price_inr,total_messages,ai_replies,instagram_accounts,automations_limit,billing_days,is_active,sort_order)
values
('free','Free',0,1500,1000,1,5,30,true,0),
('starter','Starter',299,7500,5000,1,null,30,true,1),
('pro','Pro',599,25000,15000,2,null,30,true,2),
('business','Business',1299,75000,40000,5,null,30,true,3)
on conflict (id) do nothing;

create table if not exists public.autoreply_admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid,
  admin_email text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

alter table public.autoreply_plans enable row level security;
alter table public.autoreply_admin_audit_logs enable row level security;

-- Plan writes and audit reads/writes are server-only through the service-role key.
-- Public plan reads can be added later when Billing is switched to this source.
