import crypto from 'node:crypto';
const CLIENT_ID=()=>String(process.env.GOOGLE_SHEETS_CLIENT_ID||'').trim(),CLIENT_SECRET=()=>String(process.env.GOOGLE_SHEETS_CLIENT_SECRET||'').trim();
const REDIRECT=()=>String(process.env.GOOGLE_SHEETS_REDIRECT_URI||'https://autoreplys.vercel.app/api/google-sheets/callback').trim();
const SITE='https://autoreplys.vercel.app',SB='https://dwgxmmftybxwpurgsxkx.supabase.co',PUB='sb_publishable_gEZYQWqesZH1iFysqk5sHA_fTZLQQ08',SERVICE=()=>String(process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim();
const SECRET=()=>String(process.env.GOOGLE_SHEETS_STATE_SECRET||process.env.INSTAGRAM_APP_SECRET||'').trim(),sign=(s:string)=>crypto.createHmac('sha256',SECRET()).update(s).digest('hex');
async function user(req:any){const t=String(req.headers?.authorization||'').replace(/^Bearer\s+/i,'').trim();if(!t)return null;const r=await fetch(SB+'/auth/v1/user',{headers:{apikey:PUB,Authorization:'Bearer '+t}});return r.ok?await r.json():null}
export default async function handler(req:any,res:any){const action=String(req.query?.action||'');
 if(action==='connect'){if(!CLIENT_ID()||!CLIENT_SECRET()||!SECRET())return res.status(503).json({ok:false,error:'Google Sheets OAuth environment variables are not configured.'});const u:any=await user(req);if(!u?.id)return res.status(401).json({ok:false,error:'Sign in first.'});const raw=Buffer.from(JSON.stringify({uid:u.id,at:Date.now(),n:crypto.randomBytes(8).toString('hex')})).toString('base64url');const state=raw+'.'+sign(raw);const q=new URLSearchParams({client_id:CLIENT_ID(),redirect_uri:REDIRECT(),response_type:'code',access_type:'offline',prompt:'consent',include_granted_scopes:'true',scope:'https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive.file',state});return res.redirect(302,'https://accounts.google.com/o/oauth2/v2/auth?'+q)}
 if(action==='callback'){const fail=(m:string)=>res.redirect(302,SITE+'/?sheets=error&message='+encodeURIComponent(m));if(!CLIENT_ID()||!CLIENT_SECRET()||!SERVICE()||!SECRET())return fail('Google Sheets backend is not configured.');const code=String(req.query?.code||''),state=String(req.query?.state||''),[raw,sig]=state.split('.');if(!code||!raw||!sig||sign(raw)!==sig)return fail('Invalid Google authorization response.');let st:any;try{st=JSON.parse(Buffer.from(raw,'base64url').toString())}catch{return fail('Invalid Google authorization state.')}if(!st?.uid||Date.now()-Number(st.at)>600000)return fail('Google authorization expired.');const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:CLIENT_ID(),client_secret:CLIENT_SECRET(),redirect_uri:REDIRECT(),grant_type:'authorization_code'})});const t:any=await tr.json().catch(()=>null);if(!tr.ok||!t?.access_token)return fail(t?.error_description||'Google token exchange failed.');const pr=await fetch('https://www.googleapis.com/oauth2/v2/userinfo',{headers:{Authorization:'Bearer '+t.access_token}}),p:any=await pr.json().catch(()=>({}));const data={connected:true,email:String(p.email||''),google_user_id:String(p.id||''),access_token:t.access_token,refresh_token:String(t.refresh_token||''),expires_at:Date.now()+Number(t.expires_in||3600)*1000,scope:String(t.scope||''),updated_at:new Date().toISOString()};const sr=await fetch(SB+'/rest/v1/autoreply_documents?on_conflict=user_id,collection,id',{method:'POST',headers:{apikey:SERVICE(),Authorization:'Bearer '+SERVICE(),'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({user_id:st.uid,collection:'google_sheets_connections',id:'primary',data})});if(!sr.ok)return fail('Could not securely save Google Sheets connection.');return res.redirect(302,SITE+'/?sheets=connected')}
 if(action==='status'){const u:any=await user(req);if(!u?.id)return res.status(401).json({ok:false,error:'Sign in first.'});if(!SERVICE())return res.status(503).json({ok:false,error:'Supabase service key missing.'});const r=await fetch(SB+'/rest/v1/autoreply_documents?user_id=eq.'+encodeURIComponent(u.id)+'&collection=eq.google_sheets_connections&id=eq.primary&select=data',{headers:{apikey:SERVICE(),Authorization:'Bearer '+SERVICE()}});const rows:any[]=r.ok?await r.json():[],d=rows?.[0]?.data||{};return res.status(200).json({ok:true,connected:Boolean(d.connected&&d.refresh_token),email:d.email||'',updated_at:d.updated_at||null})}
 return res.status(400).json({ok:false,error:'Unknown Google Sheets action.'});
}